version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - mr-code-challenge:/var/lib/mr-code-challenge/data

volumes:
  mr-code-challenge: {}
